version: "3"
services:
  gateway:
    build:
      dockerfile: Dockerfile
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "4000:4000"
    restart: always

  auth:
    build:
      dockerfile: Dockerfile
      context: ./authentication-microservice
    container_name: auth-service
    ports:
      - "4001:4001"
    restart: always

  course:
    build:
      dockerfile: Dockerfile
      context: ./course-microservice
    container_name: course-service
    ports:
      - "4003:4003"
    restart: always

  learner:
    build:
      dockerfile: Dockerfile
      context: ./learner-microservice
    container_name: enrollment-service
    ports:
      - "4002:4002"
    restart: always

  payment:
    build:
      dockerfile: Dockerfile
      context: ./payment-microservice
    container_name: payment-service
    ports:
      - "4004:4004"
    restart: always

  notification:
    build:
      dockerfile: Dockerfile
      context: ./notification-microservice
    container_name: notification-service
    ports:
      - "4005:4005"
    restart: always
