version: "3"
services:
  course-service1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    restart: always
    ports:
      - "4003:4003"
